# Generated by Django 5.0.3 on 2024-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(default='UwJSThs4ng', editable=False, max_length=100, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('student', models.CharField(choices=[('cewj4rjk', 'test1'), ('KJ43I9Ojkdwe', 'Daisy Oira'), ('cdsi43fre', 'Test Postman'), ('fake', 'token gen test'), ('fake2', 'gen test 2'), ('fake3', 'gen test 3'), ('fake4', 'gen test 4'), ('gnkyEb2YLw', 'token 5'), ('RigLGZdakA', 'token 7'), ('EwDZAKabzA', 'token 7'), ('MrhZtQZ-Nw', 'token 8'), ('bkVw6NOe8w', 'daisy2'), ('JPIJLcYnwA', 'daisy 3'), ('6mWzC4Pp7A', 'Crab'), ('3lH6M4jDRQ', 'Nick'), ('E3UPN9Hwxg', 'Corey'), ('I6ugOymtrQ', 'Cody'), ('sWr_3tyRbw', 'tom'), ('I3Q-po6F4g', 'Tracy'), ('VwceIB1Z8w', 'Nathan'), ('7z-bY9xvpQ', 'brandy'), ('sgo5iOo1YA', 'Rina'), ('obUectznGg', 'Ethan'), ('g9MGVBQSIA', 'Tina'), ('2OmURBkqCw', 'Gaspar'), ('MBVyFe0FAw', 'lily'), ('g5kyEJRpbw', 'Connor'), ('gSV4nxWwEQ', 'lynet'), ('QnLEhf18Wg', 'Joseph'), ('_YN9nIWN9A', 'Toto'), ('-zK3l4-H_g', 'Turner'), ('lIAVKiV5Ag', 'Yahya'), ('NS9X1z_JEQ', 'Seamus'), ('vL-KQ_RHqg', 'Felicity'), ('w8Y9WKAw9w', 'Toby'), ('d-f_GljKoQ', 'Trina'), ('DtDumyyJdg', 'Ophelia'), ('d3Qpfn10kw', 'Chai'), ('yQ-F4xW5qg', 'Booker'), ('S2RBM0b92Q', 'Reese'), ('njSmTGLPyA', 'Ferb'), ('ayxwXQEbFA', 'Ferb'), ('WzLmwTN-KQ', 'Wendy'), ('-w2bPiXHpg', 'King'), ('Xl1C91WIpw', 'Adrian'), ('OrowLBFm0g', 'Eugene'), ('Jcazennc7w', 'Henry'), ('8A5jsOo_gA', 'Tobias'), ('HUdnv26ohQ', 'Yusef'), ('PSsfk-LgDQ', 'hillary')], default=('cewj4rjk', 'test1'), max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),

    ]
