# Generated by Django 5.0.3 on 2024-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_tome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(default='7SffqWxzrw', editable=False, max_length=100, unique=True),
        ),
    ]
