# Generated by Django 5.0.3 on 2024-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_tome', '0002_alter_student_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.CharField(default='Curtin', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(default='V0LQUaOM2Q', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
    ]
