# Generated by Django 5.0.3 on 2024-05-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_tome', '0003_student_institution_alter_student_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(default='pyFuZvzLjQ', editable=False, max_length=100, unique=True),
        ),
    ]
